tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "ryota2357/pleck-jp"

brew "automake"
brew "bat"
brew "cask"
brew "clang-format"
brew "cmake"
brew "gcc"
brew "docker"
brew "docker-compose"
brew "ffmpeg"
brew "jpeg", link: true
brew "git"
brew "git-secrets"
brew "imagemagick"
brew "latexindent"
brew "lsd"
brew "mas"
brew "neovim"
brew "node"
brew "nodebrew"
brew "openssl@1.1"
brew "openssl@3"
brew "perl"
brew "pipenv"
brew "pyenv"
brew "ruby-build"
brew "rbenv"
brew "tailwindcss"
brew "telnet"
brew "tmux"
brew "tree"
brew "vim"
brew "watch"
brew "wget"
brew "yarn"
brew "zplug"
brew "zsh"

cask "alfred"
cask "ankerwork"
cask "arc"
cask "battery"
cask "brave-browser"
cask "chromedriver"
cask "deepl"
cask "font-fira-code"
cask "font-hackgen"
cask "font-hackgen-nerd"
cask "github"
cask "google-chrome"
cask "hiddenbar"
cask "iterm2"
cask "logitech-options"
cask "mactex-no-gui"
cask "microsoft-auto-update"
cask "microsoft-excel"
cask "microsoft-powerpoint"
cask "microsoft-teams"
cask "microsoft-word"
cask "monitorcontrol"
cask "pleck-jp"
cask "runcat-plugins-manager"
cask "slack"
cask "unity"
cask "unity-hub"
cask "visual-studio-code"
cask "wezterm"
cask "zoom"

mas "magnet", id: 441258766
mas "LINE", id: 539883307
mas "Microsoft Outlook", id: 985367838
mas "RunCat", id: 1429033973
mas "GoodNotes", id: 1444383602

# vim: ft=ruby
