set number
set list
set title
set belloff=all
set laststatus=2
set ruler
set cursorline
syntax on
let mapleader = "\<Space>"
set fenc=utf-8
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set whichwrap=b,s,h,l,<,>,[,],~
set listchars=tab:¦\ ,eol:↲,trail:_,extends:»,precedes:«,nbsp:%
set autoindent
set virtualedit=onemore
let &t_ti.="\e[1 q"
let &t_SI.="\e[5 q"
let &t_EI.="\e[1 q"
let &t_te.="\e[0 q"
set mouse=a
vnoremap < <gv
vnoremap > >gv
noremap x "_x
noremap X "_X
noremap c "_c
noremap C "_C
noremap s "_s
noremap S "_S
xnoremap <expr> p 'pgv"'.v:register.'y`>'
set ignorecase
set smartcase
set wrapscan
set hlsearch
nnoremap <Leader>q :nohlsearch<CR>
set incsearch
set history=100
set clipboard=unnamed
set noswapfile
set autoread
set showcmd
set ambiwidth=double
set autochdir
noremap q: :q
nnoremap <Leader>a ggVG
nnoremap <Leader>w :w<CR>
